### ISSUE TITLE
Sleep onset latency isn't computed as intended

### ISSUE THREAD

**Issue by Vaeliss** [dado93/pywearable#37]
At the moment the function `sleep.get_sleep_onset_latency` will always return 0 for any participant for any night of sleep.
This is due to the fact that sleep epochs and sleep summaries only begin when a first sleep stage is detected. 
I currently don't see a solution for this issue.

**Comment by dado93** [comment]
Probably this metric can be deleted from the available sleep metrics. As a matter of fact, it will always be equal to 0 for Garmin data.

**Comment by dado93** [comment]
With the change from supporting only Labfront to supporting multiple data sources, the metric is computed correctly. The _issue_ persists only with Garmin data, but it is not related to pywearable but to the data format of Garmin sleep data.
