### ISSUE TITLE
CPD_midpoint and CPD_duration unexpected behavior with single day computations

### ISSUE THREAD

**Issue by Vaeliss** [dado93/pywearable#60]
Both `sleep.get_cpd_midpoint` and `sleep.get_cpd_duration` assume that the period of interest is longer than a single calendar date in order to actually compute CPD metrics. If a single day is used, CPD is to be considered as simply an absolute discrepancy wrt the usual duration/midpoint (if this is not specified in `chronotype_dict` it will simply be 0, as there's not difference between the night considered and itself).

**Comment by dado93** [comment]
This should also be covered by specific tests

**Comment by dado93** [comment]
@Vaeliss do think that we could add as a parameter to these functions also the number of days to consider for the comparison? As we were discussing, if there is a day with a great difference with respect to the _normal_ range, then it would impact also the day after

**Comment by Vaeliss** [comment]
I think the current implementation is following the original paper description of how the mistiming component (i.e. the distance w.r.t. a reference, either given or inferred from data) is computed:

> Without a given individual reference (like chronotype), data can theoretically be related to either a known optimal value or simply the (circular) average of the time series.

However I agree that we might not want to consider the whole time series for such average.

As for the issue mentioned about the fact that a bad night condition strongly two successive nights, this is currently part of how CPD is thought. In order to avoid that, we might want to have a measure that computes the irregularity component with a short-term baseline (e.g. a 5-EMA), rather than the night prior alone, but this would a different metric than CPD.

Finally, I agree about adding a warning message for a single day computation.

**Comment by Vaeliss** [comment]
This was closed in the sleep-timestamp latest merge
